export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const LIST_MYCOURSES_REQUEST = "LIST_MYCOURSES_REQUEST";
export const LIST_MYCOURSES_SUCCESS = "LIST_MYCOURSES_SUCCESS";
export const LIST_MYCOURSES_FAIL = "LIST_MYCOURSES_FAIL";
export const LIST_MYCOURSES_RESET = "LIST_MYCOURSES_RESET";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";
